
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author student
 */
public class UniversityApplication extends javax.swing.JFrame {
    FunctionsList fl = new FunctionsList(); 
    public class FunctionsList {
  
    //Cancel function for Student class
    public void studentCancel(){
        studentIdTextField.setText("");
        studentNameTextField.setText("");
        studentDOBTextField.setText("");
    }
    
     public void lecturerCancel(){
        lecturerIdTextField.setText("");
        lecturerNameTextField.setText("");
        lecturerLNameTextField.setText("");
        lecturerGenderComboBox.setSelectedIndex(0);
    }
     
     public void courseCancel(){
        courseNumberTextField.setText("");
        courseNameTextField.setText("");
        
    }
}
    public UniversityApplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanelLecturer = new javax.swing.JPanel();
        labelLecturerId = new javax.swing.JLabel();
        lecturerIdTextField = new javax.swing.JTextField();
        labelLecturerName = new javax.swing.JLabel();
        labelLecturerLName = new javax.swing.JLabel();
        labelGender = new javax.swing.JLabel();
        lecturerNameTextField = new javax.swing.JTextField();
        lecturerLNameTextField = new javax.swing.JTextField();
        lecturerGenderComboBox = new javax.swing.JComboBox<>();
        lecSubmitButton = new javax.swing.JButton();
        lecCancelButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lecturerList = new javax.swing.JList<>();
        jPanelStudent = new javax.swing.JPanel();
        labelStudentId = new javax.swing.JLabel();
        studentIdTextField = new javax.swing.JTextField();
        labelStudentName = new javax.swing.JLabel();
        studentNameTextField = new javax.swing.JTextField();
        labelStudentDOB = new javax.swing.JLabel();
        studentDOBTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentList = new javax.swing.JList<>();
        studentDeleteButton = new javax.swing.JButton();
        jPanelCourse = new javax.swing.JPanel();
        labelCourseNumber = new javax.swing.JLabel();
        labelCourseName = new javax.swing.JLabel();
        courseNumberTextField = new javax.swing.JTextField();
        courseNameTextField = new javax.swing.JTextField();
        courseSubmitButton = new javax.swing.JButton();
        cancelCourseButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        courseList = new javax.swing.JList<>();
        deleteCourseButton = new javax.swing.JButton();
        modifyCourseButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        studentMenu = new javax.swing.JMenu();
        addStudentMenuItem = new javax.swing.JMenuItem();
        lecturerMenu = new javax.swing.JMenu();
        addLecturerMenuItem = new javax.swing.JMenuItem();
        courseMenu = new javax.swing.JMenu();
        addCourseMenuItem = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to the University Application !");
        getContentPane().setLayout(new java.awt.CardLayout());

        labelLecturerId.setText("Lecturer Id:");

        labelLecturerName.setText("Lecturer FName:");

        labelLecturerLName.setText("Lecturer LName:");

        labelGender.setText("Lecturer Gender:");

        lecturerGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));

        lecSubmitButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lecSubmitButton.setText("Submit");
        lecSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecSubmitButtonActionPerformed(evt);
            }
        });

        lecCancelButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lecCancelButton.setText("Cancel");
        lecCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLecturerLayout = new javax.swing.GroupLayout(jPanelLecturer);
        jPanelLecturer.setLayout(jPanelLecturerLayout);
        jPanelLecturerLayout.setHorizontalGroup(
            jPanelLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLecturerLayout.createSequentialGroup()
                .addGroup(jPanelLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLecturerLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanelLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelLecturerId, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelLecturerName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelLecturerLName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelGender, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lecturerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lecturerLNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lecturerIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lecturerGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelLecturerLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lecSubmitButton)
                        .addGap(85, 85, 85)
                        .addComponent(lecCancelButton)))
                .addGap(163, 163, 163)
                .addComponent(lecturerList, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelLecturerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lecturerGenderComboBox, lecturerIdTextField, lecturerLNameTextField, lecturerNameTextField});

        jPanelLecturerLayout.setVerticalGroup(
            jPanelLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLecturerLayout.createSequentialGroup()
                .addGroup(jPanelLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLecturerLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanelLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelLecturerId)
                            .addComponent(lecturerIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanelLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelLecturerName)
                            .addComponent(lecturerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanelLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelLecturerLName)
                            .addComponent(lecturerLNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanelLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelGender)
                            .addComponent(lecturerGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelLecturerLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLecturerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lecturerList, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(94, 94, 94)
                .addGroup(jPanelLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lecSubmitButton)
                    .addComponent(lecCancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelLecturer, "card3");

        jPanelStudent.setToolTipText("Display Student Panel!");
        jPanelStudent.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanelStudentComponentShown(evt);
            }
        });

        labelStudentId.setText("Student ID:");

        studentIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIdTextFieldActionPerformed(evt);
            }
        });

        labelStudentName.setText("Student Name:");

        labelStudentDOB.setText("Student DOB:");

        submitButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        studentList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        studentList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                studentListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(studentList);

        studentDeleteButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        studentDeleteButton.setText("Delete");
        studentDeleteButton.setEnabled(false);
        studentDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelStudentLayout = new javax.swing.GroupLayout(jPanelStudent);
        jPanelStudent.setLayout(jPanelStudentLayout);
        jPanelStudentLayout.setHorizontalGroup(
            jPanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStudentLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelStudentId, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelStudentName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelStudentDOB, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(49, 49, 49)
                .addGroup(jPanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStudentLayout.createSequentialGroup()
                        .addComponent(submitButton)
                        .addGap(76, 76, 76)
                        .addComponent(cancelButton)
                        .addGap(93, 93, 93)
                        .addComponent(studentDeleteButton))
                    .addGroup(jPanelStudentLayout.createSequentialGroup()
                        .addGroup(jPanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(studentIdTextField)
                            .addComponent(studentNameTextField)
                            .addComponent(studentDOBTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                        .addGap(87, 87, 87)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelStudentLayout.setVerticalGroup(
            jPanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStudentLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStudentLayout.createSequentialGroup()
                        .addGroup(jPanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelStudentId)
                            .addComponent(studentIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelStudentName)
                            .addComponent(studentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelStudentDOB)
                            .addComponent(studentDOBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStudentLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)))
                .addGroup(jPanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(cancelButton)
                    .addComponent(studentDeleteButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelStudent, "card2");

        labelCourseNumber.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        labelCourseNumber.setText("Course Number:");

        labelCourseName.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        labelCourseName.setText("CourseName:");

        courseSubmitButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        courseSubmitButton.setText("Submit");
        courseSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseSubmitButtonActionPerformed(evt);
            }
        });

        cancelCourseButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        cancelCourseButton.setText("Cancel");
        cancelCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelCourseButtonActionPerformed(evt);
            }
        });

        courseList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        courseList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                courseListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(courseList);

        deleteCourseButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        deleteCourseButton.setText("Delete");
        deleteCourseButton.setEnabled(false);
        deleteCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCourseButtonActionPerformed(evt);
            }
        });

        modifyCourseButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        modifyCourseButton.setText("Modify");
        modifyCourseButton.setEnabled(false);

        javax.swing.GroupLayout jPanelCourseLayout = new javax.swing.GroupLayout(jPanelCourse);
        jPanelCourse.setLayout(jPanelCourseLayout);
        jPanelCourseLayout.setHorizontalGroup(
            jPanelCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCourseLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanelCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(courseSubmitButton)
                    .addComponent(labelCourseNumber)
                    .addComponent(labelCourseName))
                .addGroup(jPanelCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCourseLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(cancelCourseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 412, Short.MAX_VALUE)
                        .addComponent(deleteCourseButton)
                        .addGap(70, 70, 70)
                        .addComponent(modifyCourseButton)
                        .addGap(130, 130, 130))
                    .addGroup(jPanelCourseLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanelCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(courseNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(courseNameTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))))
        );
        jPanelCourseLayout.setVerticalGroup(
            jPanelCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCourseLayout.createSequentialGroup()
                .addGroup(jPanelCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCourseLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanelCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCourseNumber)
                            .addComponent(courseNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanelCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCourseName)
                            .addComponent(courseNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCourseLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanelCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseSubmitButton)
                    .addComponent(cancelCourseButton)
                    .addComponent(deleteCourseButton)
                    .addComponent(modifyCourseButton))
                .addGap(124, 124, 124))
        );

        getContentPane().add(jPanelCourse, "card4");

        studentMenu.setText("Manage Students");
        studentMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentMenuActionPerformed(evt);
            }
        });

        addStudentMenuItem.setText("Add Student");
        addStudentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentMenuItemActionPerformed(evt);
            }
        });
        studentMenu.add(addStudentMenuItem);

        jMenuBar1.add(studentMenu);

        lecturerMenu.setText("Manage Lecturers");

        addLecturerMenuItem.setText("Add Lecturer");
        addLecturerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLecturerMenuItemActionPerformed(evt);
            }
        });
        lecturerMenu.add(addLecturerMenuItem);

        jMenuBar1.add(lecturerMenu);

        courseMenu.setText("Manage Courses");
        courseMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseMenuActionPerformed(evt);
            }
        });

        addCourseMenuItem.setText("Add Course");
        addCourseMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseMenuItemActionPerformed(evt);
            }
        });
        courseMenu.add(addCourseMenuItem);

        jMenuBar1.add(courseMenu);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void studentIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIdTextFieldActionPerformed

    private void addLecturerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLecturerMenuItemActionPerformed
        // display lecturer's panel
        jPanelLecturer.setVisible(true);
        jPanelStudent.setVisible(false);
        jPanelCourse.setVisible(false);
    }//GEN-LAST:event_addLecturerMenuItemActionPerformed

    private void addStudentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentMenuItemActionPerformed
        // display student panel
        jPanelStudent.setVisible(true);
        jPanelLecturer.setVisible(false);
        jPanelCourse.setVisible(false);
    }//GEN-LAST:event_addStudentMenuItemActionPerformed

    private void lecCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecCancelButtonActionPerformed
        // cancel entered data
        lecturerIdTextField.setText("");
        lecturerNameTextField.setText("");
        lecturerLNameTextField.setText("");
        lecturerGenderComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_lecCancelButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // create and add student to the list
        Student student = new Student();
        student.setStId(studentIdTextField.getText());
        student.setFName(studentNameTextField.getText());
        student.setDob(studentDOBTextField.getText());
        //add student to the list
        DefaultListModel dl = new DefaultListModel();
         ListModel l = studentList.getModel();
         for (int i=0;i<l.getSize(); i++){
          //copy from listModel into DL
          dl.addElement(l.getElementAt(i));
         }
         dl.addElement(student.toString(student));
         studentList.setModel(dl);
         //FunctionsList fl = new FunctionsList();
         fl.studentCancel();
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void studentListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_studentListValueChanged
        // define the index of the selected item of the list
                 
        int index = studentList.getSelectedIndex(); 
        if (index >=0)
        {System.out.println("Index is="+studentList.getSelectedIndex());
         studentDeleteButton.setEnabled(true);
            
        }
        
    }//GEN-LAST:event_studentListValueChanged

    private void studentDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentDeleteButtonActionPerformed
        // delete the selected element
        DefaultListModel dl = new DefaultListModel(); 
        ListModel lm = studentList.getModel();
        int index = studentList.getSelectedIndex();
        for (int i = 0; i<index; i++){
             if(index != i){
             dl.addElement(lm.getElementAt(i));
             }
            }
         studentList.setModel(dl);
    }//GEN-LAST:event_studentDeleteButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // cancel student entry
        //FunctionsList fl = new FunctionsList();
        fl.studentCancel();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void jPanelStudentComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanelStudentComponentShown
        // set focus on studentIdtextField
        studentIdTextField.requestFocus();
        
    }//GEN-LAST:event_jPanelStudentComponentShown

    private void lecSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecSubmitButtonActionPerformed
        // submit an instance of lecturer
        Lecturer lec = new Lecturer();
        lec.setId(lecturerIdTextField.getText());
        lec.setFName(lecturerNameTextField.getText());
        lec.setLName(lecturerLNameTextField.getText());
        lec.setGender((String)lecturerGenderComboBox.getSelectedItem());
        //add lecturer to the list
        //Functions.addElelemntToList(lecturerList, lec);
        DefaultListModel dl = new DefaultListModel();
         ListModel l = lecturerList.getModel();
         for (int i=0;i<l.getSize(); i++){
          //copy from listModel into DL
          dl.addElement(l.getElementAt(i));
         }
         dl.addElement(lec.toString(lec));
         lecturerList.setModel(dl);
         //FunctionsList fl = new FunctionsList();
         fl.lecturerCancel();
    }//GEN-LAST:event_lecSubmitButtonActionPerformed
 private void courseCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // cancel entered data
        courseNumberTextField.setText("");
        courseNameTextField.setText("");
 }
    private void courseSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseSubmitButtonActionPerformed
        // add course to list
        Course course = new Course();
        course.setCId(courseNumberTextField.getText());
        course.setCName(courseNameTextField.getText());
        //add student to the list
        DefaultListModel dl = new DefaultListModel();
         ListModel l = courseList.getModel();
         for (int i=0;i<l.getSize(); i++){
          //copy from listModel into DL
          dl.addElement(l.getElementAt(i));
         }
         dl.addElement(course.toString(course));
         courseList.setModel(dl);
         //FunctionsList fl = new FunctionsList();
         fl.courseCancel();
         courseNumberTextField.requestFocus();
         
    }//GEN-LAST:event_courseSubmitButtonActionPerformed

    
    private void courseMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseMenuActionPerformed
        // TODO po hedhim nje course:
                                                           
        // display student panel
       
    
    }//GEN-LAST:event_courseMenuActionPerformed

    private void studentMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentMenuActionPerformed

    private void addCourseMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseMenuItemActionPerformed
        // TODO add your handling code here:
        jPanelCourse.setVisible(true);
        jPanelLecturer.setVisible(false);
        jPanelStudent.setVisible(false);
    }//GEN-LAST:event_addCourseMenuItemActionPerformed

    private void cancelCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelCourseButtonActionPerformed
        // TODO add your handling code here:
        fl.courseCancel();
    }//GEN-LAST:event_cancelCourseButtonActionPerformed

    private void courseListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_courseListValueChanged
        // TODO add your handling code here:
        
        int index = courseList.getSelectedIndex(); 
        if (index >=0)
        {System.out.println("Index is="+courseList.getSelectedIndex());
         deleteCourseButton.setEnabled(true);
            
        }
        
    }//GEN-LAST:event_courseListValueChanged

    private void deleteCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCourseButtonActionPerformed
        // Delete course
        DefaultListModel dl = new DefaultListModel(); 
        ListModel lm = courseList.getModel();
        int index = courseList.getSelectedIndex();
        for (int i = 0; i<index; i++){
             if(index != i){
             dl.addElement(lm.getElementAt(i));
             }
            }
         courseList.setModel(dl);
    }//GEN-LAST:event_deleteCourseButtonActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UniversityApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UniversityApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UniversityApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UniversityApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UniversityApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addCourseMenuItem;
    private javax.swing.JMenuItem addLecturerMenuItem;
    private javax.swing.JMenuItem addStudentMenuItem;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cancelCourseButton;
    private javax.swing.JList<String> courseList;
    private javax.swing.JMenu courseMenu;
    private javax.swing.JTextField courseNameTextField;
    private javax.swing.JTextField courseNumberTextField;
    private javax.swing.JButton courseSubmitButton;
    private javax.swing.JButton deleteCourseButton;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanelCourse;
    private javax.swing.JPanel jPanelLecturer;
    private javax.swing.JPanel jPanelStudent;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelCourseName;
    private javax.swing.JLabel labelCourseNumber;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelLecturerId;
    private javax.swing.JLabel labelLecturerLName;
    private javax.swing.JLabel labelLecturerName;
    private javax.swing.JLabel labelStudentDOB;
    private javax.swing.JLabel labelStudentId;
    private javax.swing.JLabel labelStudentName;
    private javax.swing.JButton lecCancelButton;
    private javax.swing.JButton lecSubmitButton;
    private javax.swing.JComboBox<String> lecturerGenderComboBox;
    private javax.swing.JTextField lecturerIdTextField;
    private javax.swing.JTextField lecturerLNameTextField;
    private javax.swing.JList<String> lecturerList;
    private javax.swing.JMenu lecturerMenu;
    private javax.swing.JTextField lecturerNameTextField;
    private javax.swing.JButton modifyCourseButton;
    private javax.swing.JTextField studentDOBTextField;
    private javax.swing.JButton studentDeleteButton;
    private javax.swing.JTextField studentIdTextField;
    private javax.swing.JList<String> studentList;
    private javax.swing.JMenu studentMenu;
    private javax.swing.JTextField studentNameTextField;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
